image:
  repository: aishwaria131/sample-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000

ingress:
  enabled: false

serviceAccount:
  create: false

autoscaling:
  enabled: false  # Set to true if you want autoscaling
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80


